[workspace]
members = [
    "crates/static-typed-queries",
    "crates/static-typed-queries-macros",
    "crates/static-typed-queries-core",
]
resolver = "3"


[workspace.dependencies]

# Compile-time SQL Validation, Sanitization, Interface
sqlx = "0.9.0"

# Compile-fail Tests
trybuild = "1.0.121"

# Test Runtime
tokio = { version = "1.53.1", features = ["macros", "rt"] }
