[package]
name = "static-typed-queries-macros"
version = "0.0.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
# Procedural Macro Dependencies
proc-macro2 = { version = "1.0.107", features = ["span-locations"] }
quote = "1.0.47"
syn = { version = "3.0.6", features = ["full"] }

# Compile-time SQL Validation, Sanitization, Interface
sqlparser = { version = "0.63.0", features = ["visitor"] }

[dev-dependencies]
static-typed-queries = { path = "../static-typed-queries", features = ["all"] }
