[package]
name = "static-typed-queries-core"
version = "0.0.0"
edition = "2024"

[features]
default = []
mysql = ["sqlx/mysql"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]
sqlite-unbundled = ["sqlx/sqlite-unbundled"]

[dependencies]
sqlx = { workspace = true, optional = true }

[dev-dependencies]
static-typed-queries-core = { path = ".", features = ["mysql", "postgres", "sqlite"] }
trybuild.workspace = true
